
export const users = [
    {
        id: 1,
        username: "jdoe",
        first_name: "John",
        last_name: "Doe",
        gender: "male",
        email: "johndoe@gmail.com",
        password: "P@ssword123",
        token: "",
        role: "Admin",
    },
    {
        id: 2,
        username: "denise.w",
        first_name: "Denise",
        last_name: "Wu",
        gender: "male",
        email: "d.wu@hotmail.com",
        password: "P@ssword123",
        token: "",
        role: "User",
    },
    {
        id: 3,
        username: "alexking2210",
        first_name: "Alexandre",
        last_name: "Smith",
        gender: "Male",
        email: "alexking2210@gmail.com",
        password: "P@ssword123",
        token: "",
        role: "User",
    },
    {
        id: 4,
        username: "steveh",
        first_name: "Steve",
        last_name: "Howard",
        gender: "Male",
        email: "johndoe@gmail.com",
        password: "P@ssword123",
        token: "",
        role: "User",
    },
    {
        id: 5,
        username: "remyma",
        first_name: "Remy",
        last_name: "Martin",
        gender: "Male",
        email: "remy.martin@martininc.com",
        password: "P@ssword123",
        token: "",
        role: "User",
    },
];
